// This file is AUTO GENERATED by CMake.
#pragma once
#ifndef DREAMCAST
#include "SDL_video.h"
#endif
const static char* FILENAME_CONFIG = "./config.xml";
const static char* FILENAME_SCORES = "./hiscores";
const static char* FILENAME_TTRIAL = "./hiscores_timetrial";
const static char* FILENAME_CONT   = "./hiscores_continuous";
#ifndef DREAMCAST
const static int SDL_FLAGS = SDL_SWSURFACE | SDL_DOUBLEBUF;
#endif    
